coverage:
  range: 50..100
  round: nearest
  status:
    project: false
#      default:
#        target: 75%
#        threshold: 6%
#        base: auto
#        branches: null
comment: false
ignore:
- test/
